name = "Search Supabase Docs"
description = "Command to search through Supabase documentation and open them in your browser."
endpointURL = "https://slapcommands.vercel.app/api/docsearch/supabase"
sourceCodeURL = "https://github.com/AnishDe12020/slapcommands/blob/main/src/shared/docsearch/supabase-docs.js"
language = "javascript"
categories = ["Developer Tools", "Documentation"]

author.name = "Anish De"
author.profileURL = "https://github.com/AnishDe12020"

readme = """
This command lets you search through the [Supabase documentation](https://supabase.com/docs). You can also copy the URL to the individual pages or paste it to your current application.

The command is also [available](https://github.com/AnishDe12020/slapcommands) as a Local Command.
"""
