name = "Search Slapdash Platform Docs"
description = "Command to search through Slapdash Platform documentation and open them in your browser."
endpointURL = "https://slapcommands.vercel.app/api/docsearch/slapdash-platform"
sourceCodeURL = "https://github.com/AnishDe12020/slapcommands/blob/main/src/shared/docsearch/slapdash-platform-docs.js"
language = "javascript"
categories = ["Developer Tools", "Documentation"]

author.name = "Anish De"
author.profileURL = "https://github.com/AnishDe12020"

readme = """
This command lets you search through the [Slapdash Platform documentation](https://platform.slapdash.com/). You can also copy the URL to the individual pages or paste it to your current application.

The command is also [available](https://github.com/AnishDe12020/slapcommands) as a Local Command.
"""
