name = "Search Next.js Docs"
description = "Command to search through Next.js documentation and open them in your browser."
endpointUrl = "https://slapcommands.vercel.app/api/docsearch/next-js"
sourceCodeUrl = "https://github.com/AnishDe12020/slapcommands/blob/main/src/shared/docsearch/nextjs-docs.js"
language = "javascript"
categories = ["Developer Tools", "Productivity", "Documentation"]

author.name = "Anish De"
author.profileUrl = "https://github.com/AnishDe12020"

readme = """
This command lets you search through the [Next.js documentation](https://nextjs.org/docs) and open it
up on your browser. You can also copy the URL to the documentation and also
paste the URL to the documentation to your current application.

It is also available as a local command, details here - https://github.com/AnishDe12020/slapcommands
"""
